package com.nicolasdupouy.utilities.args.exception;

public enum ErrorCode {
	OK,
	UNEXPECTED_ARGUMENT,
	INVALID_ARGUMENT_FORMAT,
	INVALID_ARGUMENT_NAME,
	MISSING_STRING,
	MISSING_INTEGER, INVALID_INTEGER,
	MISSING_DOUBLE, INVALID_DOUBLE
}
